### ISSUE TITLE
msgpack-c version dependency

### ISSUE THREAD

**Issue by taion** [tavendo/AutobahnCpp#22]
The msgpack-c version dependency is not properly documented.

The documentation in README.md suggests using HEAD on msgpack-c/master, but this is not really a workable solution. For example, the msgpack-c developers just renamed `msgpack::type::DOUBLE` to `msgpack::type::FLOAT`.

I think it would make more sense to back out https://github.com/tavendo/AutobahnCpp/commit/b44ee2e0582923fe8e175eff1ec726582575f4e2 and specifically depend on msgpack-c 0.5.9, which will at least be a fixed target.

Additionally, the install instructions for msgpack-c are not quite correct. The C++ bindings are header-only, and thus don't require building.

**Comment by taion** [comment]
Here is the commit where the msgpack-c developers made the change I mentioned above: https://github.com/msgpack/msgpack-c/commit/737e6703df2cad06cfb16e3e0e34a02ec5212c38

**Comment by ecorm** [comment]
msgpack-c 0.5.9 does not implement v5 of the MsgPack spec. v5 of the spec has provisions for distinguishing between blob and string types.

Until the next msgpack-c is released, an easy workaround would be to set the `MSGPACK_USE_LEGACY_NAME_AS_FLOAT` macro as https://github.com/msgpack/msgpack-c/commit/737e6703df2cad06cfb16e3e0e34a02ec5212c38 suggests.

**Comment by taion** [comment]
I see. Would it make sense to specify a commit of msgpack-c to use in the install instructions, then?

**Comment by oberstet** [comment]
The install instructions are for msgpack-c head exactly for the reaons @ecorm mentions:

* the latest tagged release is 0.5.9
* 0.5.9 lacks v5 support

When msgpack-c does a new release, we can update the install instructions to 0.5.10+ (or 0.6+).

I leave this issue open ...

**Comment by ecorm** [comment]
msgpack-c now has a new release for version 1.0.0.

**Comment by taion** [comment]
Thanks!
