### ISSUE TITLE
"provide" v. "register"

### ISSUE THREAD

**Issue by taion** [tavendo/AutobahnCpp#26]
It looks like all the other Autobahn implementations use something like `session.register()` to register a new RPC method. AutobahnCpp on the other hand uses `session.provide()`. Would it make sense to change to `session.register()` for consistency?

**Comment by oberstet** [comment]
Yes, making it consistent would be better, but the problem is that `register` is a keyword in C++ - hence the different naming.

**Comment by taion** [comment]
Oops, sorry (:

**Comment by oberstet** [comment]
Nothing to be sorry about! Thanks for contributing!
