### ISSUE TITLE
Implement caller/publisher options

### ISSUE THREAD

**Issue by oberstet** [tavendo/AutobahnCpp#34]

**Comment by davidchappelle** [comment]
I have added support for call options. It came in with #51

**Comment by KrishnaPG** [comment]
Came across this while looking for `provide_options` for procedures.

How to specify `provide_options` while registering new method providers? I would like to use round-robin mechanism etc. to avoid the 'provider already registered' errors.

**Comment by KrishnaPG** [comment]
Also, the invoke values [here](http://autobahn.ws/js/reference.html#shared-registrations) define `roundrobing` as one of the possible values. - is it a typo? if not what is the `g` stand for?

**Comment by KrishnaPG** [comment]
Tried this code. But still getting `wamp.error.procedure_already_exists` error
````
autobahn::provide_options options;
options.insert_or_assign("invoke", msgpack::object("last"));

for (auto&& rpcMethod : rpcMethods)
{
	session->provide(rpcMethod.uri, rpcMethod.handler, options).then([&](boost::future<autobahn::wamp_registration> registration) {
		std::cerr << "[" << getTimestamp() << "] registered procedure: " << rpcMethod.uri << " , " << registration.get().id() << std::endl;
	});
}
````

**Comment by KrishnaPG** [comment]
Didn't want to hijack this thread. Created new issue: https://github.com/crossbario/autobahn-cpp/issues/139
