### ISSUE TITLE
Do AutobahnCpp work with boost version 1.55?

### ISSUE THREAD

**Issue by phlegx** [tavendo/AutobahnCpp#49]
I want to use the boost libraries installed from the package manager of my operating system. Do AutobahnCpp work with boost 1.55?

**Comment by oberstet** [comment]
No, you will need at least 1.56. Please see https://github.com/tavendo/AutobahnCpp#building

**Comment by phlegx** [comment]
@oberstet thank you. I have tried to code a simple example with boost::future and boost::promise. And I have read your code to get some idea. :smile:
